name: Deploy to Firebase
'on':
  push:
    branches:
      - master
    pull_request:
      - master

jobs:

  build_and_deploy_develop:
    name: Deploy to develop
    environment:
      name: desarrollo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v1
        with:
          ref: 'develop'
      - run: |
          touch .env
          echo REACT_APP_API_AUTH=${{ secrets.REACT_APP_API_AUTH }} >> .env
          echo REACT_APP_API=${{ secrets.REACT_APP_API }} >> .env
          echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env
          echo REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }} >> .env
          echo REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }} >> .env
          echo REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }} >> .env
          echo REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} >> .env
          echo REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }} >> .env
          echo REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }} >> .env
          cat .env
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.DEV_FRONT_SERVICE }}'
          channelId: live
          projectId: dev-front-startamericas
      - run: npm test


  run_sonarqube:
    name: sonarqube
    needs: [build_and_deploy_develop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'develop'
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          
      - name: Node install dependencies
        run: npm install

      - name: Run unit e2e test
        run: npm test 

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build_and_deploy_master:
    name: deploy to production
    needs: [build_and_deploy_develop, run_sonarqube]
    environment:
      name: produccion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - run: |
          touch .env
          echo REACT_APP_API_AUTH=${{ secrets.REACT_APP_API_AUTH }} >> .env
          echo REACT_APP_API=${{ secrets.REACT_APP_API }} >> .env
          echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env
          echo REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }} >> .env
          echo REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }} >> .env
          echo REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }} >> .env
          echo REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} >> .env
          echo REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }} >> .env
          cat .env
      - run: npm ci && npm run build
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.PROD_FRONT_SERVIVE }}'
          channelId: live
          projectId: startamericastogether


