name: Deploy to Firebase
'on':
  push:
    branches:
      - master
      - feature/*
jobs:
  deploy_to_production:
    name: deploy_production
    environment:
      name: produccion
    runs-on: ubuntu-latest
    #needs: [build_and_deploy, run_sonarqube]
    steps:
      - run: echo now we are in master
      - run: echo this will be deploy soon