name: Deploy to Firebase
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
jobs:
  deploy_to_production:
    name: deploy_production
    environment:
      name: produccion
    runs-on: ubuntu-latest
    needs: [build_and_deploy, run_sonarqube]
    steps:
      - run: deploy in develop ready, sonarqube ready
      - run: production ready